# Generated by Django 3.2.13 on 2022-05-13 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='website_images', verbose_name='Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is active')),
                ('is_hero', models.BooleanField(default=False, verbose_name='Is hero')),
                ('is_divider', models.BooleanField(default=False, verbose_name='Is divider')),
                ('is_gallery', models.BooleanField(default=False, verbose_name='Is banner')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone')),
                ('whatsapp', models.CharField(max_length=15, verbose_name='Whatsapp Number')),
                ('social_media', models.CharField(max_length=15, verbose_name='Social Media')),
                ('gender', models.CharField(max_length=20, verbose_name='Gender')),
                ('pronouns', models.CharField(max_length=25, verbose_name='Pronouns')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('country', models.CharField(max_length=25, verbose_name='Country of Residence')),
                ('nationality', models.CharField(max_length=25, verbose_name='Nationality')),
                ('sector', models.CharField(max_length=255, verbose_name='Volunteering Sector')),
                ('mode_of_communication', models.CharField(max_length=50, verbose_name='Preffered Mode of Communication')),
                ('image', models.ImageField(blank=True, upload_to='volunteer_images', verbose_name='Image')),
                ('photo_sharing_consent', models.BooleanField(verbose_name='Photo Sharing Consent')),
                ('nominee1_name', models.CharField(max_length=100, verbose_name='Nominee 1 Name')),
                ('nominee1_social_media', models.CharField(max_length=50, verbose_name='Nominee 1 Social Media')),
                ('nominee1_country', models.CharField(max_length=50, verbose_name='Nominee 1 Country')),
                ('nominee1_contact', models.CharField(max_length=50, verbose_name='Nominee 1 Contact')),
                ('nominee2_name', models.CharField(max_length=100, verbose_name='Nominee 2 Name')),
                ('nominee2_social_media', models.CharField(max_length=50, verbose_name='Nominee 2 Social Media')),
                ('nominee2_country', models.CharField(max_length=50, verbose_name='Nominee 2 Country')),
                ('nominee2_contact', models.CharField(max_length=50, verbose_name='Nominee 2 Contact')),
                ('story_title', models.CharField(max_length=100)),
                ('story_overview', models.TextField(default='')),
                ('story_content', tinymce.models.HTMLField()),
                ('story_image', models.ImageField(upload_to='story_image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='Story Category')),
                ('story_sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.subcategory', verbose_name='Story Sub Category')),
            ],
            options={
                'verbose_name': 'Volunteer',
                'verbose_name_plural': 'Volunteers',
            },
        ),
    ]
