# Generated by Django 3.2.13 on 2022-05-13 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteer',
            name='social_media',
            field=models.CharField(max_length=150, verbose_name='Social Media'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='whatsapp',
            field=models.CharField(max_length=25, verbose_name='Whatsapp Number'),
        ),
    ]
