# Generated by Django 3.2.13 on 2023-09-07 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20230907_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMemberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('designation', models.CharField(blank=True, max_length=200, null=True, verbose_name='Designation')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('image', models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Image')),
                ('serial', models.IntegerField(default=0, verbose_name='Serial')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Facebook Link')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Twitter Link')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Instagram Link')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Linkedin Link')),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
                'ordering': ['serial'],
            },
        ),
    ]
